/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.clsEmpleado;
import clases.clsProducto;
import controladores.ctrEmpleado;
import controladores.ctrInicio;
import java.awt.List;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.LinkedList;
import static javafx.beans.binding.Bindings.equal;
import static javafx.beans.binding.Bindings.equal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author OscarArb
 */
public class incio extends javax.swing.JFrame {
    //Creamos un DefaulTablemode para dar un modelo a nuestra tabla
    DefaultTableModel dtm = new DefaultTableModel();
    ctrInicio ctrInicio = new ctrInicio();
    ctrEmpleado ctrEmpleado = new ctrEmpleado();
    /**
     * Creates new form incio
     */
    public incio() {
        initComponents();
        //realizo un nuevo objeto que contiene la imagen icono
        setIconImage(new ImageIcon(getClass().getResource("/multimedia/cacha.jpg")).getImage());
        this.setLocationRelativeTo(null);
        //Realizo la cabecera de la tabla
        String[] titulo = new String[]{"Cantidad","Producto","V.Unit","V.Total"};
        dtm.setColumnIdentifiers(titulo);
        tabla_productos.setModel(dtm);
        numerofactura.setEnabled(false);
        txt_totalApagar.setEnabled(false);
        
    }
    void agregarProd_tabla(){
        dtm.addRow(new Object[]{
            txt_cantidad.getText(),combobox_productos.getSelectedItem(),txt_precios.getText(),txt_total.getText()
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_precios = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        combobox_productos = new javax.swing.JComboBox<>();
        txt_totalApagar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cant_pago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_registrarF = new javax.swing.JButton();
        btn_imprimirF = new javax.swing.JButton();
        btn_eliminarF = new javax.swing.JButton();
        btn_editarArticulo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chekNuevaFactura = new javax.swing.JCheckBox();
        txtNumeroFactura = new javax.swing.JLabel();
        txt_idCliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        numerofactura = new javax.swing.JTextField();
        comboMes = new javax.swing.JComboBox<>();
        comboDia = new javax.swing.JComboBox<>();
        txtAno = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        telefonoCliente = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_devuelta = new javax.swing.JLabel();
        ValorGasto = new javax.swing.JPanel();
        comboBox_empleados = new javax.swing.JComboBox<>();
        btn_busqueda = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_fecha_pagos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_valorQuincena = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_Gastos = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        txt_PagoEmpleado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cant_gasto = new javax.swing.JTextField();
        txt_detalleGasto = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        btn_agregarGasto = new javax.swing.JButton();
        btn_editarGasto = new javax.swing.JButton();
        btn_eliminarGasto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        fechaGasto = new javax.swing.JTextField();
        PagarQuincena = new javax.swing.JButton();
        ImrimirColilla = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jEmpleado = new javax.swing.JCheckBox();
        jProducto = new javax.swing.JCheckBox();
        jCliente = new javax.swing.JCheckBox();
        jProveedor = new javax.swing.JCheckBox();
        labelValor = new javax.swing.JLabel();
        txtNombreDetalle = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtFechasPago = new javax.swing.JTextField();
        txtValorquincena = new javax.swing.JTextField();
        btn_registro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CACHAROS Y DROGAS EL CACHA SD");
        setBackground(new java.awt.Color(255, 102, 255));
        setFont(new java.awt.Font("Agency FB", 3, 10)); // NOI18N
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 197, 236));

        jLabel11.setBackground(new java.awt.Color(204, 0, 204));
        jLabel11.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel11.setText("Bienvenid0(A)");

        jTabbedPane3.setBackground(new java.awt.Color(51, 197, 236));
        jTabbedPane3.setToolTipText("");
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane3.setName("gg"); // NOI18N

        jPanel6.setBackground(new java.awt.Color(51, 197, 236));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Producto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Precio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("IVA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total");

        txt_iva.setText("0");

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        combobox_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_productosActionPerformed(evt);
            }
        });

        txt_totalApagar.setText("0");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("Total A Pagar:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setText("Cant. Pago:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("Devuelta:");

        btn_registrarF.setBackground(new java.awt.Color(0, 153, 204));
        btn_registrarF.setText("Registrar");

        btn_imprimirF.setBackground(new java.awt.Color(0, 153, 204));
        btn_imprimirF.setText("Imprimir");

        btn_eliminarF.setBackground(new java.awt.Color(0, 153, 204));
        btn_eliminarF.setText("Eliminar");
        btn_eliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarFActionPerformed(evt);
            }
        });

        btn_editarArticulo.setBackground(new java.awt.Color(0, 153, 204));
        btn_editarArticulo.setText("Editar");

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton2.setText("Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chekNuevaFactura.setBackground(new java.awt.Color(0, 153, 204));
        chekNuevaFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chekNuevaFactura.setText("Nueva Factura");
        chekNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekNuevaFacturaActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel23.setText("Nombre: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Factura Nº:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Fecha:");

        numerofactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerofacturaActionPerformed(evt);
            }
        });

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "OctubreNoviembre", "Diciembre" }));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });

        comboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaActionPerformed(evt);
            }
        });

        txtAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("CLIENTE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btn_calcular.setBackground(new java.awt.Color(0, 153, 204));
        btn_calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Venta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Vendedor1", "Vendedor2", "Vendedor3" }));

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Detalles", "V.Unitario", "V.Total"
            }
        ));
        jScrollPane5.setViewportView(tabla_productos);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        txt_devuelta.setBackground(new java.awt.Color(255, 255, 255));
        txt_devuelta.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(txt_total, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_iva, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_precios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(chekNuevaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(combobox_productos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(numerofactura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_totalApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_cant_pago, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                    .addComponent(txt_devuelta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox1)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(btn_eliminarF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_registrarF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_imprimirF)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_editarArticulo)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroFactura))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chekNuevaFactura)
                        .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combobox_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(numerofactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_precios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btn_calcular)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_totalApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cant_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_devuelta, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarF)
                    .addComponent(btn_registrarF)
                    .addComponent(btn_imprimirF)
                    .addComponent(btn_editarArticulo))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Facturar", jPanel4);

        ValorGasto.setBackground(new java.awt.Color(51, 197, 236));

        comboBox_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_empleadosActionPerformed(evt);
            }
        });

        btn_busqueda.setBackground(new java.awt.Color(0, 153, 204));
        btn_busqueda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_busqueda.setText("Busqueda");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Fecha de pago: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Valor Quincenal:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Control De Gastos");

        lista_Gastos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista_Gastos);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("TOTAL A PAGAR:");

        jLabel16.setText("Cantidad");

        jLabel17.setText("Detalle");

        jLabel18.setText("Valor");

        btn_agregarGasto.setBackground(new java.awt.Color(0, 153, 204));
        btn_agregarGasto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_agregarGasto.setText("Agregar");
        btn_agregarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarGastoActionPerformed(evt);
            }
        });

        btn_editarGasto.setBackground(new java.awt.Color(0, 153, 204));
        btn_editarGasto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_editarGasto.setText("Editar");

        btn_eliminarGasto.setBackground(new java.awt.Color(0, 153, 204));
        btn_eliminarGasto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_eliminarGasto.setText("Eliminar");

        jLabel19.setText("Fecha");

        PagarQuincena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PagarQuincena.setText("PAGAR");
        PagarQuincena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarQuincenaActionPerformed(evt);
            }
        });

        ImrimirColilla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ImrimirColilla.setText("Imprimir Colilla");

        btnConsultar.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ValorGastoLayout = new javax.swing.GroupLayout(ValorGasto);
        ValorGasto.setLayout(ValorGastoLayout);
        ValorGastoLayout.setHorizontalGroup(
            ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValorGastoLayout.createSequentialGroup()
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ValorGastoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ValorGastoLayout.createSequentialGroup()
                                .addComponent(comboBox_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_busqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultar))
                            .addGroup(ValorGastoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fecha_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addComponent(txt_valorQuincena, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_PagoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(ValorGastoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ValorGastoLayout.createSequentialGroup()
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cant_gasto)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel17))
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txt_detalleGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel18)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel19))
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ValorGastoLayout.createSequentialGroup()
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_agregarGasto)
                                    .addComponent(PagarQuincena))
                                .addGap(42, 42, 42)
                                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ValorGastoLayout.createSequentialGroup()
                                        .addComponent(btn_editarGasto)
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_eliminarGasto))
                                    .addComponent(ImrimirColilla)))))
                    .addGroup(ValorGastoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        ValorGastoLayout.setVerticalGroup(
            ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValorGastoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_busqueda)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_fecha_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_valorQuincena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_PagoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cant_gasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_detalleGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarGasto)
                    .addComponent(btn_editarGasto)
                    .addComponent(btn_eliminarGasto))
                .addGap(55, 55, 55)
                .addGroup(ValorGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PagarQuincena)
                    .addComponent(ImrimirColilla))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Nomina", ValorGasto);

        jPanel2.setBackground(new java.awt.Color(51, 197, 236));

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Detalle", "Cantidad", "Valor Unitario", "Valor De Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaInventario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Inventario De Productos");

        jButton3.setText("CONSULTA VENTAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CREDITOS");

        jButton5.setText("REGISTRA NOVEDADES");

        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))
                                    .addComponent(jLabel21))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane3.addTab("Inventario", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 197, 236));

        labelNombre.setText("Nombre");

        labelTelefono.setText("Telefono");

        labelFecha.setText("Fechas de pago");

        jEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        jEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmpleado.setText("Empleado");
        jEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpleadoActionPerformed(evt);
            }
        });

        jProducto.setBackground(new java.awt.Color(204, 204, 255));
        jProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jProducto.setText("Producto");
        jProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductoActionPerformed(evt);
            }
        });

        jCliente.setBackground(new java.awt.Color(204, 204, 255));
        jCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCliente.setText("Cliente");
        jCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteActionPerformed(evt);
            }
        });

        jProveedor.setBackground(new java.awt.Color(204, 204, 255));
        jProveedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jProveedor.setText("Proveedor");
        jProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProveedorActionPerformed(evt);
            }
        });

        labelValor.setText("Valor Quincena");

        btn_registro.setBackground(new java.awt.Color(255, 153, 255));
        btn_registro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registro.setText("Rejistrar");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(txtNombreDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechasPago, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFecha))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtValorquincena, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btn_registro))
                            .addComponent(labelValor)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProveedor)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpleado)
                    .addComponent(jProducto)
                    .addComponent(jCliente)
                    .addComponent(jProveedor))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelTelefono)
                    .addComponent(labelFecha)
                    .addComponent(labelValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechasPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorquincena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registro))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Registro", jPanel3);

        jPanel1.setBackground(new java.awt.Color(51, 197, 236));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Caja", jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(269, 269, 269))
            .addComponent(jTabbedPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProveedorActionPerformed
        // TODO add your handling code here:
        if (jProveedor.isSelected()){
            labelNombre.setText("Nombres");
            labelTelefono.setText("Telefono");
            labelFecha.setText("Direccion");
            labelValor.setText("Empresa");
            jCliente.setSelected(false);
            jEmpleado.setSelected(false);
            jProducto.setSelected(false);

        }
    }//GEN-LAST:event_jProveedorActionPerformed

    private void jClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteActionPerformed
        // TODO add your handling code here:
        if (jCliente.isSelected()){
            labelNombre.setText("Nombres");
            labelTelefono.setText("Telefono");
            labelFecha.setText("Direccion");
            labelValor.setText("Id");
            jProveedor.setSelected(false);
            jEmpleado.setSelected(false);
            jProducto.setSelected(false);
            txtValorquincena.setEnabled(true);

        }
    }//GEN-LAST:event_jClienteActionPerformed

    private void jProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductoActionPerformed
        // TODO add your handling code here:
        if (jProducto.isSelected()){
            labelNombre.setText("Detalles");
            labelTelefono.setText("Precio");
            labelFecha.setText("No Aplica");
            labelValor.setText("No Aplica");
            jProveedor.setSelected(false);
            jEmpleado.setSelected(false);
            jCliente.setSelected(false);
            txtValorquincena.setEnabled(false);
            txtFechasPago.setEnabled(false);

        }
    }//GEN-LAST:event_jProductoActionPerformed

    private void jEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpleadoActionPerformed
        // TODO add your handling code here:
        if (jEmpleado.isSelected()){
            labelNombre.setText("Nombre");
            labelTelefono.setText("Telefono");
            labelFecha.setText("Fechas De Pago");
            labelValor.setText("Valor Quincena");
            jProveedor.setSelected(false);
            jProducto.setSelected(false);
            jCliente.setSelected(false);
            txtValorquincena.setEnabled(true);
            txtFechasPago.setEnabled(true);

        }
    }//GEN-LAST:event_jEmpleadoActionPerformed

    private void PagarQuincenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarQuincenaActionPerformed
        // TODO add your handling code here:
        
        String empleado = (String) comboBox_empleados.getSelectedItem(); 
        System.out.println(empleado);
        String pagar = txt_PagoEmpleado.getText();
        if (empleado.equals("")){
            JOptionPane.showMessageDialog(this,"No ha seleccionado un empleado");
        }else{
            if (JOptionPane.showConfirmDialog(this, "¿Desea "+pagar+" A "+ empleado+"?")==0){
                JOptionPane.showMessageDialog(this,"Se ha cancelado quincena por: "+pagar+" a "+ empleado);
            }
        }
    }//GEN-LAST:event_PagarQuincenaActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed
        // TODO add your handling code here:
        comboBox_empleados.removeAllItems();
        String modelo = ctrInicio.ListarEmpleado();
        System.out.println(modelo);
        String[] filas = modelo.split(",");
        for (int i = 0; i < filas.length; i++){

            comboBox_empleados.insertItemAt(filas[i], i);
        }
    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void comboBox_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_empleadosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboBox_empleadosActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        // TODO add your handling code here:
        boolean estado;
        if (jEmpleado.isSelected()){
            String nombre = txtNombreDetalle.getText();
            String telefono = txtTel.getText();
            String fechapago = txtFechasPago.getText();
            int valorquincena = Integer.parseInt(txtValorquincena.getText());
            
            

            //Crear obteto
            clsEmpleado empleado = new clsEmpleado(nombre, telefono, fechapago, valorquincena);
            estado = ctrEmpleado.Crear(empleado);
            if (estado){
                //System.out.println(empleado.getNombre());
                JOptionPane.showMessageDialog(this,"El objeto se agrego correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"El objeto NO se agrego correctamente");
            }

        }else if (jProducto.isSelected()){
            String nombre = txtNombreDetalle.getText();
            int valorproducto = Integer.parseInt(txtTel.getText());
            if (nombre.equals("")){
                JOptionPane.showMessageDialog(this,"El campo producto esta vacio");
            }if(valorproducto == 0){
                JOptionPane.showMessageDialog(this,"EL campo valor no se encuentra digitado, asegurese de escribir numeros sin puntos");
            }
            
            System.out.println("Aqui deberia salir un mensaje en pantalla  donde especifica que la funcion no se encuentra activa");
            JOptionPane.showMessageDialog(this,"Aun no se ha configurado esta funcion");

            //Crea objeto de tipo Ejectutivo
            //clsEjecutivo ejecutivo = new clsEjecutivo(oficio, tarjetaProfesional, tarjetaProfesional, tipoEmpleado, nombre, primerApellido, segundoApellido, identificacion);
            //estado = ctrEmpleado.Crear(ejecutivo);
            //if (estado){
               // JOptionPane.showMessageDialog(this,"El ejcutivo se agrego correctamente");
            //}else{
              //  JOptionPane.showMessageDialog(this,"El ejecutivo NO se agrego correctamente");
            //}

        }else if(jCliente.isSelected()){
            String nombreCliente = txtNombreDetalle.getText();
            String telefonoCliente = txtTel.getText();
            String direccionCliente = txtFechasPago.getText();
            int idCliente = Integer.parseInt(txtValorquincena.getText());
            //Crear obteto
            clsEmpleado empleado = new clsEmpleado(nombreCliente, telefonoCliente, direccionCliente, idCliente);
            estado = ctrEmpleado.Crear_cliente(empleado);
            if (estado){
                //System.out.println(empleado.getNombre());
                JOptionPane.showMessageDialog(this,"Ahora "+nombreCliente+"Es nuevo cliente");
            }else{
                JOptionPane.showMessageDialog(this,"No se pudo agregar el nuevo cliente, Intentelo mas tarde");
            }
            
        }
        /*else{
            String nombre = txtNombre.getText();
            String primerApellido = txtPrimerApellido.getText();
            String segundoApellido = txtSegundoApellido.getText();
            int identificacion = Integer.parseInt(txtIdentificacion.getText());
            String oficio = txtOficio.getText();
            String tarjetaProfesional = txtTarjetaProfesional.getText();
            String tipoEmpleado = cbTipoEmpleado.getSelectedItem().toString();
            //Crear obtejo de tipo Gerente
            clsGerente gerente = new clsGerente(oficio, tarjetaProfesional, tipoEmpleado, nombre, primerApellido, segundoApellido, identificacion);
            //Crear objeto de tipo gerente
            estado = ctrEmpleado.Crear(gerente);
            if (estado){
                JOptionPane.showMessageDialog(this,"El objeto se agrego correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"El objeto NO se agrego correctamente");
            }

        }*/
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Ventas venta = new Ventas();
        venta.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chekNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekNuevaFacturaActionPerformed
        // TODO add your handling code here:
        
        telefonoCliente.setText("");
        txt_precios.setText("");
        txt_cantidad.setText("");
        txt_total.setText("");
        txt_idCliente.setText("");
        txt_NombreCliente.setText("");
        txt_totalApagar.setText("0");
        txt_cant_pago.setText("");
        txt_devuelta.setText("0");
        combobox_productos.removeAllItems();
        String modelo = ctrInicio.ListarProducto();
        System.out.println(modelo);
        String[] filas = modelo.split(",");
        for (int i = 0; i < filas.length; i++){
            

            combobox_productos.insertItemAt(filas[i], i);
        }
        
        int ultima = ctrInicio.UltimaFactura();
        System.out.println(ultima);
        ultima = ultima +1;
        numerofactura.setText(String.valueOf(ultima));
        
    }//GEN-LAST:event_chekNuevaFacturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*int cantidadProductos = Integer.parseInt(txt_cantidad.getText());
        int precioProducto = Integer.parseInt(txt_precios.getText());

        int total = cantidadProductos * precioProducto;
        String tot = String.valueOf(total);
        txt_total.setText(tot);
        */
        try {
            clsProducto empleadoAuxiliar = null;
            String producto = (String) combobox_productos.getSelectedItem();
         
            empleadoAuxiliar = ctrInicio.Consultar_producto(producto);
            if (empleadoAuxiliar != null) {
                int valor = empleadoAuxiliar.getValorproducto();
                String valo = String.valueOf(valor);
                txt_precios.setText(valo);
                
            } else {
                JOptionPane.showMessageDialog(this, "Es posible que el cliente buscado, no este registrado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hay Datos vacios o erroneos");
            System.out.println("Hay datos sin diligenciar o erroneos");
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combobox_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_productosActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:ç
        int totalApagar = Integer.parseInt(txt_totalApagar.getText());
           try {
            int totall = Integer.parseInt( txt_total.getText());
            
            if(totall > 0){
                agregarProd_tabla();
                totalApagar = totalApagar + totall;
                txt_totalApagar.setText(String.valueOf(totalApagar));
            }else{
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"¡Es posible que tengas campos vacios o sin calcular!");
            System.out.println("Campos Vacios error  ");
        }
           
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        // TODO add your handling code here:
        String nombreMes = (String) comboMes.getSelectedItem();
        System.out.println(nombreMes);
        String anno = (String) txtAno.getSelectedItem();
        if (nombreMes.equals("Febrero")){
            if (anno.equals("2024")){
                comboDia.removeAllItems();
            comboDia.addItem("1");comboDia.addItem("2");comboDia.addItem("3"); comboDia.addItem("4");comboDia.addItem("5");comboDia.addItem("6"); comboDia.addItem("7");comboDia.addItem("8");comboDia.addItem("9");comboDia.addItem("10");comboDia.addItem("11");comboDia.addItem("12");  
            comboDia.addItem("13");comboDia.addItem("14");comboDia.addItem("15"); comboDia.addItem("16");comboDia.addItem("17");comboDia.addItem("18"); comboDia.addItem("19");comboDia.addItem("20");comboDia.addItem("21");comboDia.addItem("22");comboDia.addItem("23");comboDia.addItem("24");
            comboDia.addItem("25");comboDia.addItem("26");comboDia.addItem("27"); comboDia.addItem("28");comboDia.addItem("29");
            }else{
            comboDia.removeAllItems();
            comboDia.addItem("1");comboDia.addItem("2");comboDia.addItem("3"); comboDia.addItem("4");comboDia.addItem("5");comboDia.addItem("6"); comboDia.addItem("7");comboDia.addItem("8");comboDia.addItem("9");comboDia.addItem("10");comboDia.addItem("11");comboDia.addItem("12");  
            comboDia.addItem("13");comboDia.addItem("14");comboDia.addItem("15"); comboDia.addItem("16");comboDia.addItem("17");comboDia.addItem("18"); comboDia.addItem("19");comboDia.addItem("20");comboDia.addItem("21");comboDia.addItem("22");comboDia.addItem("23");comboDia.addItem("24");
            comboDia.addItem("25");comboDia.addItem("26");comboDia.addItem("27"); comboDia.addItem("28");
            }    
        }else if (nombreMes.equals("Abril") || nombreMes.equals("Junio")|| nombreMes.equals("Septiembre")|| nombreMes.equals("Noviembre")){
            comboDia.removeAllItems();
            comboDia.addItem("1");comboDia.addItem("2");comboDia.addItem("3"); comboDia.addItem("4");comboDia.addItem("5");comboDia.addItem("6"); comboDia.addItem("7");comboDia.addItem("8");comboDia.addItem("9");comboDia.addItem("10");comboDia.addItem("11");comboDia.addItem("12");  
            comboDia.addItem("13");comboDia.addItem("14");comboDia.addItem("15"); comboDia.addItem("16");comboDia.addItem("17");comboDia.addItem("18"); comboDia.addItem("19");comboDia.addItem("20");comboDia.addItem("21");comboDia.addItem("22");comboDia.addItem("23");comboDia.addItem("24");
            comboDia.addItem("25");comboDia.addItem("26");comboDia.addItem("27"); comboDia.addItem("28");comboDia.addItem("29");comboDia.addItem("30");
            
        }else{
            comboDia.removeAllItems();
            comboDia.addItem("1");comboDia.addItem("2");comboDia.addItem("3"); comboDia.addItem("4");comboDia.addItem("5");comboDia.addItem("6"); comboDia.addItem("7");comboDia.addItem("8");comboDia.addItem("9");comboDia.addItem("10");comboDia.addItem("11");comboDia.addItem("12");  
            comboDia.addItem("13");comboDia.addItem("14");comboDia.addItem("15"); comboDia.addItem("16");comboDia.addItem("17");comboDia.addItem("18"); comboDia.addItem("19");comboDia.addItem("20");comboDia.addItem("21");comboDia.addItem("22");comboDia.addItem("23");comboDia.addItem("24");
            comboDia.addItem("25");comboDia.addItem("26");comboDia.addItem("27"); comboDia.addItem("28");comboDia.addItem("29");comboDia.addItem("30");comboDia.addItem("31");
        }
    }//GEN-LAST:event_comboMesActionPerformed

    private void btn_agregarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarGastoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        try {
            clsEmpleado empleadoAuxiliar = null;
            int identificacion = Integer.parseInt( txt_idCliente.getText());
         
            empleadoAuxiliar = ctrEmpleado.Consultar_cliente(identificacion);
            if (empleadoAuxiliar != null) {
                System.out.println(empleadoAuxiliar.getNombre());
                txt_NombreCliente.setText(empleadoAuxiliar.getNombre());
                telefonoCliente.setText(empleadoAuxiliar.getTelefono());
                
            } else {
                JOptionPane.showMessageDialog(this, "Es posible que el cliente buscado, no este registrado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hay Datos vacios o erroneos");
            System.out.println("Hay datos sin diligenciar o erroneos");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        try {
            int cantidad = Integer.parseInt( txt_cantidad.getText());
            int porcentaje = Integer.parseInt( txt_iva.getText());
            System.out.println("Valor de cantidad, "+cantidad+" valor de iva, "+porcentaje);
            if(porcentaje > 0){
                int valorProducto = Integer.parseInt( txt_precios.getText());
                int precio_porcentaje = valorProducto / 100 * porcentaje ;
                int valorMasPorcentaje = valorProducto + precio_porcentaje;
                int total = valorMasPorcentaje * cantidad;
                //convierto el valor total de entero a string para mostrarlo en la interfaz de usuario
                String valoramostrar = String.valueOf(total);
                txt_total.setText(valoramostrar);
            }else{
                int valorProducto = Integer.parseInt( txt_precios.getText());
                int total = valorProducto * cantidad;
                //convierto el valor total de entero a string para mostrarlo en la interfaz de usuario
                String valoramostrar = String.valueOf(total);
                txt_total.setText(valoramostrar);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hay Datos vacios o erroneos");
            System.out.println("Hay datos sin diligenciar o erroneos");
        }
    
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void numerofacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerofacturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numerofacturaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        int tpago = Integer.parseInt(txt_totalApagar.getText()); 
        int cant_pago = Integer.parseInt(txt_cant_pago.getText()); 
        int devuelta = cant_pago - tpago ; 
        txt_devuelta.setText(String.valueOf(devuelta));
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_eliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarFActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_eliminarFActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(incio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new incio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImrimirColilla;
    private javax.swing.JButton PagarQuincena;
    private javax.swing.JPanel ValorGasto;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btn_agregarGasto;
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_editarArticulo;
    private javax.swing.JButton btn_editarGasto;
    private javax.swing.JButton btn_eliminarF;
    private javax.swing.JButton btn_eliminarGasto;
    private javax.swing.JButton btn_imprimirF;
    private javax.swing.JButton btn_registrarF;
    private javax.swing.JButton btn_registro;
    private javax.swing.JTextField cant_gasto;
    private javax.swing.JCheckBox chekNuevaFactura;
    private javax.swing.JComboBox<String> comboBox_empleados;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> combobox_productos;
    private javax.swing.JTextField fechaGasto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCliente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JCheckBox jEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox jProducto;
    private javax.swing.JCheckBox jProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelValor;
    private javax.swing.JList<String> lista_Gastos;
    private javax.swing.JTextField numerofactura;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JComboBox<String> txtAno;
    private javax.swing.JTextField txtFechasPago;
    private javax.swing.JTextField txtNombreDetalle;
    private javax.swing.JLabel txtNumeroFactura;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtValorquincena;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_PagoEmpleado;
    private javax.swing.JTextField txt_cant_pago;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_detalleGasto;
    private javax.swing.JLabel txt_devuelta;
    private javax.swing.JTextField txt_fecha_pagos;
    private javax.swing.JTextField txt_idCliente;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_precios;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_totalApagar;
    private javax.swing.JTextField txt_valorQuincena;
    // End of variables declaration//GEN-END:variables
}
